export const savedMoney = [
  {
    id: 1,
    day: "S",
    saved: 10,
    expense: 30,
  },
  {
    id: 2,
    day: "M",
    saved: 20,
    expense: 25,
  },
  {
    id: 3,
    day: "T",
    saved: 20,
    expense: 20,
  },
  {
    id: 4,
    day: "W",
    saved: 10,
    expense: 30,
  },
  {
    id: 5,
    day: "T",
    saved: 16,
    expense: 22,
  },
  {
    id: 6,
    day: "F",
    saved: 15,
    expense: 28,
  },
  {
    id: 7,
    day: "S",
    saved: 24,
    expense: 29,
  },
];

export const recentTransactionData = [
  {
    id: 1,
    Day: 1,
    Week: 1,
    Month: "Nov 1",
    Year: "2018",
    Amount: 30,
  },
  {
    id: 2,
    Day: 2,
    Week: 2,
    Month: "Nov 4",
    Year: "2019",
    Amount: 20,
  },
  {
    id: 3,
    Day: 3,
    Week: 3,
    Month: "Nov 8",
    Year: "2020",
    Amount: 32,
  },
  {
    id: 4,
    Day: 4,
    Week: 4,
    Month: "Nov 12",
    Year: "2021",
    Amount: 10,
  },
  {
    id: 5,
    Day: 5,
    Week: 5,
    Month: "Nov 16",
    Year: "2022",
    Amount: 38,
  },
];

export const suggestionData = [
  "Saanvi",
  "Anya",
  "Aadhya",
  "Aaradhya",
  "Ananya",
  "Pari",
  "Anika",
  "Navya",
  "Angel",
  "Diya",
  "Myra",
  "Sara",
  "Iraa",
  "Ahana",
  "Anvi",
  "Prisha",
  "Riya",
  "Aarohi",
  "Anaya",
  "Akshara",
  "Eva",
  "Shanaya",
  "Kyra",
  "Siya",
  "Aarav",
  "Vihaan",
  "Vivaan",
  "Ananya",
  "Diya",
  "Advik",
  "Kabir",
  "Anaya",
  "Aarav",
  "Vivaan",
  "Aditya",
  "Vivaan",
  "Vihaan",
  "Arjun",
  "Vivaan",
  "Reyansh",
  "Mohammed",
  "Sai",
  "Arnav",
  "Aayan",
  "Krishna",
  "Ishaan",
  "Shaurya",
  "Atharva",
  "Advik",
  "Pranav",
  "Advaith",
  "Aaryan",
  "Dhruv",
  "Kabir",
  "Ritvik",
  "Aarush",
  "Kian",
  "Darsh",
];

export const portfolioData = [
  {
    id: 1,
    name: "TCS",
    Quantity: 36,
    price: 3327,
    cap: "Large Cap",
    color: "green",
  },
  {
    id: 2,
    name: "KPITTECH",
    Quantity: 42,
    price: 711,
    cap: "Small Cap",
    color: "blue",
  },
  {
    id: 3,
    name: "DEEPAKFERT",
    Quantity: 64,
    price: 809,
    cap: "MEdiam Cap",
    color: "#273c75",
  },
  {
    id: 4,
    name: "HDFC",
    Quantity: 36,
    price: 2714,
    cap: "Large Cap",
    color: "#1289A7",
  },
  {
    id: 5,
    name: "VEDL",
    Quantity: 24,
    price: 313,
    cap: "Mediam Cap",
    color: "#006266",
  },
  {
    id: 6,
    name: "L&T",
    Quantity: 86,
    price: 2199,
    cap: "Large Cap",
    color: "#e15f41",
  },
  {
    id: 7,
    name: "ADANIPORTS",
    Quantity: 92,
    price: 901,
    cap: "Large Cap",
    color: "#ffd32a",
  },
];

export const riskRewardData = [
  {
    id: 1,
    fundName: "HSBC Liquid Fund",
    CreditRiskScore: 9.0,
    StressSectorScore: 5.0,
    SensitiveIssuerScore: 6.0,
    InterestRateScore: 6.0,
    LiquidityScore: 6.0,
    CompositeConcentrationRiskScore: 7.0,
    StandardDeviationScore: 7.0,
    AssetClassExposureScore: 4.5,
    TotalRiskScore: 6.8,
    RankBasedOnRisk: 3,
    YTM: 6.0,
    CompositePerformanceScore: 7.6,
    ConsistencyScore:8.0,
    TotalReturnScore: 7.2,
    RankBasedOnReturns: 3,
    OverallScore: 6.9,
    OverallRanking:1,
  },
  {
    id: 2,
    fundName: "IDFC Cash Fund",
    CreditRiskScore: 10.0,
    StressSectorScore: 8.0,
    SensitiveIssuerScore:6.0,
    InterestRateScore: 4.5,
    LiquidityScore: 9.0,
    CompositeConcentrationRiskScore: 6.3,
    StandardDeviationScore: 6.0,
    AssetClassExposureScore: 7.3,
    TotalRiskScore: 7.6,
    RankBasedOnRisk: 1,
    YTM: 5.0,
    CompositePerformanceScore: 3.8,
    ConsistencyScore:6.0,
    TotalReturnScore: 4.9,
    RankBasedOnReturns: 10,
    OverallScore: 6.8,
    OverallRanking:2,
  },
  {
    id: 3,
    fundName: "UTI Liquid Cash Plan",
    CreditRiskScore: 5.0,
    StressSectorScore: 10.0,
    SensitiveIssuerScore: 5.0,
    InterestRateScore: 7.5,
    LiquidityScore: 10.0,
    CompositeConcentrationRiskScore: 3.7,
    StandardDeviationScore: 9.0,
    AssetClassExposureScore: 8.8,
    TotalRiskScore: 6.8,
    RankBasedOnRisk: 2,
    YTM: 1.0,
    CompositePerformanceScore: 5.6,
    ConsistencyScore:10.0,
    TotalReturnScore: 5.5,
    RankBasedOnReturns: 6,
    OverallScore: 6.4,
    OverallRanking: 3,
  },
  {
    id: 4,
    fundName: "Axis Liquid Fund ",
    CreditRiskScore: 6.0,
    StressSectorScore: 3.0,
    SensitiveIssuerScore: 6.0,
    InterestRateScore: 6.0,
    LiquidityScore: 5.0,
    CompositeConcentrationRiskScore: 8.7,
    StandardDeviationScore: 5.0,
    AssetClassExposureScore: 3.3,
    TotalRiskScore: 5.5,
    RankBasedOnRisk: 7,
    YTM: 5.0,
    CompositePerformanceScore: 9.0,
    ConsistencyScore:10.0,
    TotalReturnScore: 8.0,
    RankBasedOnReturns: 2,
    OverallScore: 6.3,
    OverallRanking:4,
  },
  {
    id: 5,
    fundName: "DSP Liquidity Fund ",
    CreditRiskScore: 5.0,
    StressSectorScore: 7.0,
    SensitiveIssuerScore: 2.0,
    InterestRateScore: 10.0,
    LiquidityScore: 7.0,
    CompositeConcentrationRiskScore: 5.7,
    StandardDeviationScore: 9.0,
    AssetClassExposureScore: 5.5,
    TotalRiskScore: 6.0,
    RankBasedOnRisk: 4,
    YTM: 4.0,
    CompositePerformanceScore: 4.2,
    ConsistencyScore:7.0,
    TotalReturnScore: 5.1,
    RankBasedOnReturns: 8,
    OverallScore: 5.7,
    OverallRanking:5,
  },
  {
    id: 6,
    fundName: "Tata Liquid Fund",
    CreditRiskScore: 8.0,
    StressSectorScore: 5.0,
    SensitiveIssuerScore: 6.0,
    InterestRateScore: 3.0,
    LiquidityScore: 2.0,
    CompositeConcentrationRiskScore: 3.7,
    StandardDeviationScore: 2.0,
    AssetClassExposureScore: 3.5,
    TotalRiskScore: 4.9,
    RankBasedOnRisk: 8,
    YTM: 9.0,
    CompositePerformanceScore: 7.2,
    ConsistencyScore:5.0,
    TotalReturnScore: 7.1,
    RankBasedOnReturns: 4,
    OverallScore: 5.6,
    OverallRanking:6,
  },
  {
    id: 7,
    fundName: "Nippon India Liquid Fund",
    CreditRiskScore: 7.0,
    StressSectorScore: 6.0,
    SensitiveIssuerScore: 6.0,
    InterestRateScore: 4.0,
    LiquidityScore: 5.0,
    CompositeConcentrationRiskScore: 5.0,
    StandardDeviationScore: 3.0,
    AssetClassExposureScore: 7.0,
    TotalRiskScore: 5.7,
    RankBasedOnRisk: 5,
    YTM: 6.0,
    CompositePerformanceScore: 4.0,
    ConsistencyScore:5.0,
    TotalReturnScore: 5.0,
    RankBasedOnReturns: 9,
    OverallScore: 5.5,
    OverallRanking:7,
  },
  {
    id: 8,
    fundName: "ICICI Pru Liquid Fund ",
    CreditRiskScore: 6.0,
    StressSectorScore: 4.0,
    SensitiveIssuerScore: 5.0,
    InterestRateScore: 8.0,
    LiquidityScore: 3.0,
    CompositeConcentrationRiskScore: 7.3,
    StandardDeviationScore: 8.0,
    AssetClassExposureScore: 3.5,
    TotalRiskScore: 5.6,
    RankBasedOnRisk: 6,
    YTM: 4.0,
    CompositePerformanceScore: 2.2,
    ConsistencyScore:3.0,
    TotalReturnScore: 3.1,
    RankBasedOnReturns:11,
    OverallScore: 4.9,
    OverallRanking:8,
  },
  {
    id: 9,
    fundName: "Aditya Birla SL Liquid Fund",
    CreditRiskScore: 1.0,
    StressSectorScore: 1.0,
    SensitiveIssuerScore: 6.0,
    InterestRateScore: 5.0,
    LiquidityScore: 1.0,
    CompositeConcentrationRiskScore: 10.0,
    StandardDeviationScore: 4.0,
    AssetClassExposureScore: 2.3,
    TotalRiskScore: 3.3,
    RankBasedOnRisk: 12,
    YTM: 10.0,
    CompositePerformanceScore: 9.0,
    ConsistencyScore:6.0,
    TotalReturnScore: 8.3,
    RankBasedOnReturns: 1,
    OverallScore: 4.8,
    OverallRanking:9,
  },
  
  {
    id: 10,
    fundName: "Kotak Liquid Fund ",
    CreditRiskScore: 3.0,
    StressSectorScore: 9.0,
    SensitiveIssuerScore: 4.0,
    InterestRateScore: 2.0,
    LiquidityScore: 8.0,
    CompositeConcentrationRiskScore: 1.7,
    StandardDeviationScore: 1.0,
    AssetClassExposureScore: 7.8,
    TotalRiskScore: 4.2,
    RankBasedOnRisk: 10,
    YTM: 8.0,
    CompositePerformanceScore: 4.4,
    ConsistencyScore:3.0,
    TotalReturnScore: 5.1,
    RankBasedOnReturns: 7,
    OverallScore: 4.5,
    OverallRanking:10,
  },
  {
    id: 11,
    fundName: "HDFC Liquid Fund",
    CreditRiskScore: 4.0,
    StressSectorScore: 2.0,
    SensitiveIssuerScore: 1.0,
    InterestRateScore: 1.0,
    LiquidityScore: 6.0,
    CompositeConcentrationRiskScore: 5.3,
    StandardDeviationScore: 5.0,
    AssetClassExposureScore: 5.3,
    TotalRiskScore: 3.5,
    RankBasedOnRisk: 11,
    YTM: 7.0,
    CompositePerformanceScore: 5.6,
    ConsistencyScore:5.0,
    TotalReturnScore: 5.9,
    RankBasedOnReturns: 5,
    OverallScore: 4.2,
    OverallRanking:11,
  },
  {
    id: 12,
    fundName: "SBI Liquid Fund",
    CreditRiskScore: 2.0,
    StressSectorScore: 6.0,
    SensitiveIssuerScore: 3.0,
    InterestRateScore: 8.5,
    LiquidityScore: 4.0,
    CompositeConcentrationRiskScore: 1.7,
    StandardDeviationScore: 6.0,
    AssetClassExposureScore: 7.5,
    TotalRiskScore: 4.4,
    RankBasedOnRisk: 9,
    YTM: 2.0,
    CompositePerformanceScore: 3.4,
    ConsistencyScore:1.0,
    TotalReturnScore: 2.1,
    RankBasedOnReturns: 12,
    OverallScore: 3.7,
    OverallRanking:12,
  },
];

